// Script para añadir películas reales famosas con imágenes de TMDB
import { db } from "../src/lib/db";

async function addRealMovies() {
  console.log("🎬 Añadiendo películas reales famosas con imágenes de TMDB...");

  // Películas reales famosas con imágenes de TMDB (públicas)
  const realMovies = [
    {
      title: "Interestelar",
      description: "Un grupo de exploradores viaja a través de un agujero de gusano en busca de un nuevo hogar para la humanidad. Una épica odisea espacial de Christopher Nolan.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
      banner: "https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fcZEEK4Uo.jpg",
      category: "Ciencia Ficción",
      genre: "Ciencia Ficción",
      year: 2014,
      duration: 169,
      rating: 8.7,
      ageRating: "+13",
      trending: true,
      featured: true,
    },
    {
      title: "El Caballero de la Noche",
      description: "Batman se enfrenta al Joker, un criminal psicópata que quiere sembrar el caos en Gotham City. La obra maestra de Christopher Nolan.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDuxqFnY4egK6X4qzWT.jpg",
      banner: "https://image.tmdb.org/t/p/original/hqkIcbrOHL86UncnHIsHVcVmzue.jpg",
      category: "Acción",
      genre: "Acción",
      year: 2008,
      duration: 152,
      rating: 9.0,
      ageRating: "+16",
      trending: true,
      featured: true,
    },
    {
      title: "Origen",
      description: "Un ladrón que roba secretos corporativos a través de la tecnología de sueños compartidos recibe la tarea inversa de plantar una idea en la mente de un CEO.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvrhNJkRJM.jpg",
      banner: "https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H8Py2Ri.jpg",
      category: "Ciencia Ficción",
      genre: "Ciencia Ficción",
      year: 2010,
      duration: 148,
      rating: 8.8,
      ageRating: "+13",
      trending: true,
    },
    {
      title: "Matrix",
      description: "Un hacker descubre que la realidad es una simulación creada por máquinas y se une a la resistencia para liberar a la humanidad.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkJPOhBxNXvq.jpg",
      banner: "https://image.tmdb.org/t/p/original/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg",
      category: "Ciencia Ficción",
      genre: "Ciencia Ficción",
      year: 1999,
      duration: 136,
      rating: 8.7,
      ageRating: "+16",
      featured: true,
    },
    {
      title: "Parásitos",
      description: "La familia Kim traza un plan para infiltrarse en la rica familia Park. Una sátira social ganadora del Oscar.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
      banner: "https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
      category: "Drama",
      genre: "Drama",
      year: 2019,
      duration: 132,
      rating: 8.6,
      ageRating: "+16",
      trending: true,
    },
    {
      title: "El Padrino",
      description: "El patriarca de una dinastía del crimen organizado transfiere el control de su imperio clandestino a su hijo reacio. La obra maestra de Coppola.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
      banner: "https://image.tmdb.org/t/p/original/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
      category: "Drama",
      genre: "Drama",
      year: 1972,
      duration: 175,
      rating: 9.2,
      ageRating: "+16",
      trending: true,
    },
    {
      title: "Pulp Fiction",
      description: "Las vidas de dos sicarios, un boxeador, la esposa de un gánster y dos asaltantes se entrelazan en cuatro historias de violencia y redención.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPiJYhIBhaI.jpg",
      banner: "https://image.tmdb.org/t/p/original/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
      category: "Drama",
      genre: "Drama",
      year: 1994,
      duration: 154,
      rating: 8.9,
      ageRating: "+18",
      featured: true,
    },
    {
      title: "Vengadores: Endgame",
      description: "Después de los eventos devastadores de Infinity War, los Vengadores se reúnen para revertir las acciones de Thanos y restaurar el universo.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
      banner: "https://image.tmdb.org/t/p/original/7RyHsO4yudtNd8RnqsJYf6sShJx.jpg",
      category: "Acción",
      genre: "Acción",
      year: 2019,
      duration: 181,
      rating: 8.4,
      ageRating: "+13",
      trending: true,
      featured: true,
    },
    {
      title: "Avatar",
      description: "Un marine parapléjico es enviado a la luna Pandora, donde se encuentra entre seguir órdenes y proteger el mundo que siente como su hogar.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
      banner: "https://image.tmdb.org/t/p/original/Yc9q6QuWrDf3TnE2Zqx7p7ZEl7.jpg",
      category: "Ciencia Ficción",
      genre: "Ciencia Ficción",
      year: 2009,
      duration: 162,
      rating: 7.9,
      ageRating: "+13",
      featured: true,
    },
    {
      title: "Coco",
      description: "Un niño que sueña con ser músico entra al Land of the Dead para encontrar a su tatarabuelo, un legendario cantante.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/gGEsBPAijhLVUFpk7py1e9Ud6W9.jpg",
      banner: "https://image.tmdb.org/t/p/original/eKiLGtgheRs3t5p0wKjBA2f6sM5.jpg",
      category: "Animación",
      genre: "Animación",
      year: 2017,
      duration: 105,
      rating: 8.4,
      ageRating: "ATP",
    },
    {
      title: "El Señor de los Anillos: El Retorno del Rey",
      description: "Frodo y Sam continúan su viaje hacia Mordor para destruir el Anillo, mientras los demás lideran la última batalla contra las fuerzas de Sauron.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/rCzpDGLbOoPwLjyEjHCb2FtvOPI.jpg",
      banner: "https://image.tmdb.org/t/p/original/9De2f3R5v6nirmbL9mUx5tFObXb.jpg",
      category: "Aventura",
      genre: "Aventura",
      year: 2003,
      duration: 201,
      rating: 8.9,
      ageRating: "+13",
      trending: true,
    },
    {
      title: "Titanic",
      description: "Una artista de 17 años y un joven artista se enamoran a bordo del Titanic en su viaje inaugural. Una de las películas más taquilleras de la historia.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
      banner: "https://image.tmdb.org/t/p/original/79ezH5Zfa2zWd1QqP3u8O5KJXfX.jpg",
      category: "Romance",
      genre: "Romance",
      year: 1997,
      duration: 194,
      rating: 7.9,
      ageRating: "+13",
    },
    {
      title: "Gladiador",
      description: "Un general romano traicionado busca venganza como gladiador en el Coliseo. La épica histórica de Ridley Scott.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H7mifJ4sPcR.jpg",
      banner: "https://image.tmdb.org/t/p/original/hND7xAaxxBgaIspp9iMsaD8lrRv.jpg",
      category: "Acción",
      genre: "Acción",
      year: 2000,
      duration: 155,
      rating: 8.5,
      ageRating: "+16",
    },
    {
      title: "La La Land",
      description: "Una actriz y un músico de jazz se enamoran en Los Ángeles mientras persiguen sus sueños. Un musical moderno ganador de 6 Oscars.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoEdgCD018rDMwm0J.jpg",
      banner: "https://image.tmdb.org/t/p/original/fp6X6yhgcxzxCpmM0EVC6V9B5qz.jpg",
      category: "Romance",
      genre: "Romance",
      year: 2016,
      duration: 128,
      rating: 8.0,
      ageRating: "+13",
    },
    {
      title: "Mad Max: Furia en el Camino",
      description: "En un mundo post-apocalíptico, Max se une a Furiosa para huir de un tirano y su ejército. Una de las mejores películas de acción de la historia.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
      banner: "https://image.tmdb.org/t/p/original/gqrnQA6Xppdl8vIb2eJc58VC1tW.jpg",
      category: "Acción",
      genre: "Acción",
      year: 2015,
      duration: 120,
      rating: 8.1,
      ageRating: "+16",
      trending: true,
    },
    {
      title: "Spider-Man: Un Nuevo Universo",
      description: "Miles Morales se convierte en Spider-Man y cruza dimensiones para conocer a otros Spider-People. Ganadora del Oscar a Mejor Animación.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/iiXdDOuAd4onZ9Y2oT8MC9yJ7aE.jpg",
      banner: "https://image.tmdb.org/t/p/original/iiZZdQfs7HCmA8RR7RjJj5NgU3z.jpg",
      category: "Animación",
      genre: "Animación",
      year: 2018,
      duration: 117,
      rating: 8.4,
      ageRating: "ATP",
    },
    {
      title: "Joker",
      description: "En Gotham City, el comediante mentalmente perturbado Arthur Fleck es ignorado y maltratado por la sociedad. Luego emprende una espiral descendente.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDfEzMUI.jpg",
      banner: "https://image.tmdb.org/t/p/original/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
      category: "Drama",
      genre: "Drama",
      year: 2019,
      duration: 122,
      rating: 8.4,
      ageRating: "+18",
      trending: true,
      featured: true,
    },
    {
      title: "Guasón",
      description: "Un comediante fracasado se transforma en el criminal Joker en una Gotham City cada vez más desigual. Ganadora del León de Oro.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/VolkswagenGTIReview.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDfEzMUI.jpg",
      banner: "https://image.tmdb.org/t/p/original/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
      category: "Drama",
      genre: "Drama",
      year: 2019,
      duration: 122,
      rating: 8.4,
      ageRating: "+18",
      isAdult: false,
    },
    {
      title: "Dune",
      description: "Paul Atreides, un joven brillante y talentoso, debe viajar al planeta más peligroso del universo para asegurar el futuro de su familia y su pueblo.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgVzXaoTI3IjA.jpg",
      banner: "https://image.tmdb.org/t/p/original/jYEW5xZkZk2IZc4uL3U2Z5Z3m5t.jpg",
      category: "Ciencia Ficción",
      genre: "Ciencia Ficción",
      year: 2021,
      duration: 155,
      rating: 8.0,
      ageRating: "+13",
      trending: true,
      featured: true,
    },
    {
      title: "El Rey León",
      description: "El joven Simba debe reclamar su trono como rey de la Sabana después del asesinato de su padre Mufasa a manos de su tío Scar.",
      type: "MP4",
      url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
      thumbnail: "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpNhIdV.jpg",
      banner: "https://image.tmdb.org/t/p/original/wYwoQqO7BaVBuvsGID8tn3luYJ4.jpg",
      category: "Animación",
      genre: "Animación",
      year: 1994,
      duration: 88,
      rating: 8.5,
      ageRating: "ATP",
    },
  ];

  let added = 0;
  for (const m of realMovies) {
    const exists = await db.content.findFirst({ where: { title: m.title } });
    if (!exists) {
      await db.content.create({ data: m as any });
      console.log(`  ✅ ${m.title} (${m.year}) — ★${m.rating}`);
      added++;
    }
  }

  console.log(`\n🎉 ${added} películas reales añadidas!`);
}

addRealMovies()
  .catch((e) => {
    console.error("❌ Error:", e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
